database/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from website import settings
from . import views
app_name = 'database'

urlpatterns = [
    url(r'^$', views.index, name='home'),

    # tables
    url(r'^data/Samples$', views.sample_table.as_view(), name='sample-data'),
    url(r'^data/Alleles$', views.alleles_table.as_view(), name='allele-data'),

    url(r'^Graph/', views.presenting_graph.as_view(), name='graph-present'),

    # genotype urls handler
    url(r'^genotype/(?P<sample_name>[\w\-]+)$', views.down_geno, name='down-geno'),
    url(r'^genotype_graph/(?P<sample_name>[\w\-]+)/(?P<html>[0-1])$', views.genotype_graph, name='geno-graph'),
    url(r'^genotype_stats/(?P<sample_name>[\w\-]+)$', views.down_geno_stats, name='down-stats'),

    # hapotype urls handler
    url(r'^haplotype/(?P<id>[\w\-]+)$', views.down_haplotype, name='down-haplotype'),
    url(r'^haplotype_graph/(?P<id>[\w\-]+)/(?P<html>[0-1])$', views.haplotype_graph, name='haplotype-graph'),
    url(r'^User_Guide/', views.guide.as_view(), name='user-guide'),

    url(r'^Explore_Data$', views.explore.as_view(), name='explore-data'),

    url(r'^Licensing$', views.licensing.as_view(), name='licensing'),
]


#user handler add to url patterns in case of adding users
"""
    url(r'^register$', views.UserFormView.as_view(), name='register'),
    url(r'^login$', views.login.as_view(), name='login'),
    url(r'^logout$', views.logout, name='logout'),"""

website/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('database.urls')),

]

database/views.py
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from django.contrib import messages
from django.db.models import Q, Count
from urllib import parse

from .forms import *
from scripts import graphs, export_data, exportR_data, export_genotypes
from website.settings import SCRATCH_ROOT, BASE_DIR, APACHE_SEND
from .hold_global_vars import *

from itertools import chain
from wsgiref.util import FileWrapper
from collections import defaultdict

from datetime import datetime
import zipfile, os, math, datetime
import json

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import generic_dna

from io import StringIO

from .apps import commit_id
from .novel_checks import check_novel_confidence

##########################################################################################################
#
#     ********************* SEND FILE ********************************
#
#     Send file via apache mod_xsendfile, or stream if we don't have it
#
##########################################################################################################

def send_file(filename, content_type, disposition):
    if APACHE_SEND:
        resp = HttpResponse()
        resp['X-Sendfile'] = filename
    else:
        # check that the file is in a configured location
        if os.path.join(BASE_DIR, 'uploads') not in filename and SCRATCH_ROOT not in filename:
            print('Only files in BASE_DIR/uploads and SCRATCH_ROOT can be sent to the user.')
            return ''
        resp = HttpResponse(open(filename, 'rb').read())

    resp['Content-Type'] = content_type
    resp['Content-Disposition'] = disposition
    return resp


##########################################################################################################
#
#     ********************* HOMEPAGE ********************************
#
##########################################################################################################

def index(request):
    template = 'homepage.html'
    all_gene = Gene.objects.all()
    context = {'all_gene': all_gene, 'commit_id': commit_id}
    return render(request, template,  context)


##########################################################################################################
#
#     ********************* SAMPLES PAGE ********************************
#
##########################################################################################################

class sample_table(View):
    template_name = 'tables/samples.html'
    form_class = SamplesSearchForm
    advance = SamplesAdvanceSearchForm
    filter_by_gene = SampleFilterByGene
    filter_samples_by_gene = SampleFilterByAlleles
    haplotype_graph_form = HaplotypeGraphForm

    ##########################################################################################################
    #
    #     ****************** EXPORT THE DATA THROUGH ZIP FILE *****************************
    #
    ##########################################################################################################

    def export_sample_table(self, name, all_samples):
        genotypes_folder = "Genotypes"
        genotypes_stats_folder = "Genotypes_stats"
        haplotypes_folder = "Haplotypes"

        titles = ["SAMPLE", "SUBJECT", "NAME_IN_PAPER", "SEX", "AGE", "ETHNICITY", "STUDY_GROUP", "DIAGNOSIS", "ORGANISM",
                  "TISSUE", "CELL_TYPE", "CELL_SUBSET_TYPE", "ISOTYPE", "TARGET_LOCUS(IG)", "TARGET_SUBSTRATE", "UMI", "SEQUENCING_PLATFORM",
                  "SEQUENCING_LENGTH", "REVERSE_PCR_PRIMER_LOCATION", "FORWARD_PCR_PRIMERS_LOCATION", "TOTAL_READS", "PROJECT",
                  "LAB_ADDRESS", "RESEARCHER", "NUMBER_OF_SUBJECTS", "NUMBER_OF_SAMPLES", "PAPER", "CONTACT",
                  "STUDY_ID", "PUBLICATION_URL", "Preprocessing", "ALIGNER_TOOL", "ALIGNER_VERSION",
                  "GERMLINE_GENE_SET", "GENOTYPING_TOOL", "GENOTYPING_VERSION", "HAPLOTYPING_TOOL", "HAPLOTYPING_VERSION",
                  "GENOTYPE_FILE", "GENOTYPE_STATISTICS", "HAPLOTYPE_BY", "HAPLOTYPE_FILES"]

        samples = []
        genotypes = []
        genotypes_stats = []
        haplotypes = []

        for s in all_samples:
            sample = []
            sample.append(s.name)

            patient = s.patient
            sample += [patient.name, patient.name_in_paper, patient.sex, patient.age, patient.ethnic, patient.cohort, patient.status]

            tissue = s.tissue_pro
            sample += [tissue.species, tissue.tissue, tissue.cell_type, tissue.sub_cell_type, tissue.isotype]
            sample.append(s.chain)

            protocol = s.seq_protocol
            sample += [protocol.helix, protocol.umi, protocol.sequencing_platform, protocol.sequencing_length,
                       protocol.primers_3_location, protocol.primers_5_location]
            sample.append(s.row_reads)

            study = s.study
            sample += [study.name, study.institute, study.researcher, study.num_subjects, study.num_samples,
                        study.reference, study.contact, study.accession_id, study.accession_reference]

            geno = s.geno_detection
            sample += [geno.prepro_tool, geno.aligner_tool, geno.aligner_ver, geno.aligner_reference, geno.geno_tool,
                       geno.geno_ver, geno.haplotype_tool, geno.haplotype_ver]

            sample.append(os.path.join(genotypes_folder, os.path.basename(s.genotype.name)))
            genotypes.append(s.genotype.name)
            if s.genotype_stats:
                sample.append(os.path.join(genotypes_stats_folder, os.path.basename(s.genotype_stats.name)))
                genotypes_stats.append(s.genotype_stats.name)
            else:
                sample.append("")

            haplotypes_by = []
            haplotypes_files = []

            if s.haplotype:
                for hap_file in s.haplotype.all():
                    haplotypes.append(hap_file.file.name)
                    haplotypes_files.append(os.path.join(haplotypes_folder, os.path.basename(hap_file.file.name)))
                    haplotypes_by.append(hap_file.by_gene)


            haplotypes_by = ", ".join(haplotypes_by)
            haplotypes_files = ", ".join(haplotypes_files)

            sample.append(haplotypes_by)
            sample.append(haplotypes_files)

            # append the list of fileds of one sample into the table f samples
            samples.append(sample)

        metafile = export_data.output("metadata.tab", titles, samples)
        name = os.path.join(SCRATCH_ROOT, name) + '.zip'

        with zipfile.ZipFile(name, 'w') as myzip:
            myzip.write(metafile, os.path.basename(metafile))
            for f in genotypes:
                path = os.path.join(BASE_DIR, 'uploads/', f)
                myzip.write(path, os.path.join(genotypes_folder, os.path.basename(path)))
            for hap in haplotypes:
                path = os.path.join(BASE_DIR, 'uploads/', hap)
                myzip.write(path, os.path.join(haplotypes_folder, os.path.basename(path)))
            for geno_stats in genotypes_stats:
                path = os.path.join(BASE_DIR, 'uploads/', geno_stats)
                myzip.write(path, os.path.join(genotypes_stats_folder, os.path.basename(path)))

            myzip.close()

        return send_file(name, 'application/zip', 'Content-Disposition')

    ##########################################################################################################
    #
    #     genotypes_graph - CREATE MULTIPLE GENOTYPES AND EXPORT
    #
    ##########################################################################################################

    def genotypes_graph(self, request, name, samples, genes, file_type, with_pseudo_genes):
        samples = samples.values_list('name', 'genotype')
        genes = genes.values_list('name')
        genes = list(chain.from_iterable(genes))
        with_pseudo_genes = bool(with_pseudo_genes)

        genotypes_graph = export_genotypes.merge_genotypes(samples, name, genes, type_html=file_type, pseudo_genes=with_pseudo_genes)

        if not genotypes_graph:
            return False

        if not file_type:
            return send_file(genotypes_graph, 'application/pdf', 'attachment; filename=genotypes_graph.pdf')
        else:
            genotypes_graph = genotypes_graph.split("graphs/")[1]
            template = "temp/display_genotype.html"
            context = {'html_file': genotypes_graph, }
            return render(request, template, context)


    ##########################################################################################################
    #
    #     genotypes_heatmap - CREATE HEATMAP GENOTYPES AND EXPORT
    #
    ##########################################################################################################

    def genotypes_heatmap(self, request, name, samples, genes, kdiff, file_type):
        samples = samples.values_list('name', 'genotype')
        genes = genes.values_list('name')
        genes = list(chain.from_iterable(genes))
        genotypes_graph = export_genotypes.genotypes_heatmap(samples, name, genes, kdiff, type_html=file_type)

        if not genotypes_graph:
            return False

        if not file_type:
            return send_file(genotypes_graph, 'application/pdf', 'attachment; filename=genotypes_heatmap.pdf')
        else:
            genotypes_graph = genotypes_graph.split("graphs/")[1]
            template = "temp/display_genotype.html"
            context = {'html_file': genotypes_graph, }
            return render(request, template, context)


    ##########################################################################################################
    #
    #     haplotypes_heatmap - CREATE MULTIPLE HAPLOTYPES HEATMAP AND EXPORT
    #

database/templates/explore.html
{% load static %}


<!doctype html>
<html lang=”en”>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Explore Data</title>

    {% include 'links.html' %}
    <link rel="stylesheet" href="{% static 'css/vdjbase.css' %}">
    <link rel="stylesheet" href="{% static 'css/explore.css' %}">
</head>

<!-- ################################# body ######################## -->
<body>
{% include 'navbar.html' %}

<div class="w3-container">

<!-- ################################################################ -->
<!--                 title "Explore VDJbase Data"                     -->
<!-- ################################################################ -->
     <div id="frame-content">
        <div id="template" class="template product product-feature">
            <br><br>
            <div class="feature-column">
                <div class="feature-hero-unit" style="background-image: linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), url({%  static 'images/explore_header.jpg' %});">
                    <div class="feature-container">
                        <h1>Explore VDJbase Data</h1>

                        <!-- <a class="button secondary" href="https://pdf-temp-files.s3.amazonaws.com/ee9a864f087c4f948c73badd5b30dfbf/index.html" download="ExploreVDJbase" target="_blank"><i class="fa fa-file-text-o" aria-hidden="true" style="margin-right:10px;"></i>DOWNLOAD EXPLANATION SHEET</a>
                        -->
                        <a class="button secondary" href="{% static 'images/ExplorePage_graph_explanations.pdf' %}" download="ExploreVDJbase" target="_blank"><i class="fa fa-file-text-o" aria-hidden="true" style="margin-right:10px;"></i>DOWNLOAD EXPLANATION SHEET</a>
                    </div>
                </div>
            </div>
        </div>
     </div>


<!-- ################################################################ -->
<!--                       Dataset summary                            -->
<!-- ################################################################ -->
    <div class="w3-container">
        <h1 style="color:#009999;font-size:300%;text-align:left"><b>Summary of VDJbase Dataset </b></h1>
    </div>

    <!--Table and divs that hold the pie charts-->

     <div class="w3-row w3-chart-row">
        <div class="w3-col l5 m12 s12 w3-chart" id="piechart_div" ></div>
        <div class="w3-col l3 m12s12 w3-chart" id="barchart_div" ></div>
        <div class="w3-col l4 m12s12 w3-chart" id="piechart_div3"></div>
     </div>

</div>

<div class="w3-container">
        <div class="w3-row w3-chart-row">
            <div class="w3-col l9 m12">
                <div class="w3-container"   style="width:1050px; height:600px; overflow:auto;margin-left: auto; margin-right: auto;">
                <table style="width: 1000px; height: auto;" cellspacing="0" cellpadding="1" border="1" width="300">
                    <tr>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Project ID</th>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Accession ID</th>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Institute</th>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Subjects</th>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Samples</th>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Link to the paper</th>
                      <th style='position: sticky; top:0; background: #ddd; height: 5px;'>Accession link</th>
                    </tr>

                    {% for study in allstudies %}
                    <tr>
                    <td>{{ study.name }}</td>
                    <td>{{ study.accession_id }}</td>
                    <td>{{ study.institute }}</td>
                    <td>{{ study.num_subjects }}</td>
                    <td>{{ study.num_samples }}</td>
                    <td><a href="{{ study.reference }}" target="_blank"><i class="fa fa-file-text-o"></i></a></td>
                    <td><a href="{{ study.accession_reference }}" target="_blank"><i class="fa fa-file-text-o"></i></a></td>

                    </tr>
                    {% endfor %}
                </table>
                </div>
            </div>

                <div class = "w3-col l3 m12 w3-chart" id="piechart_div4"></div>
        </div>
</div>

<br>
<br>
<!-- ################################################################ -->
<!--                   Some interesting results                        -->
<!-- ################################################################ -->

<!--border line + title -->
<div class="w3-content" style="max-width:1200px">
    <hr>
    <div class="w3-row">
        <div class="w3-container">
            <h1 style="color:#009999;font-size:300%;text-align:left"><b>Some of the interesting results revealed by VDJbase</b></h1>
        </div>
    </div>

    <!-- The Allele distribution Section -->

    <div class="w3-row">
        <div class="w3-container">
        <div class="w3-col l4 m12">
          <h1 class="xlarge-font"><b>Allele Distribution</b></h1>
          <h1 class="large-font" style="color:MediumSeaGreen;"><b>selected IGHJ throughout the database</b></h1>
        </div>
        <div class="w3-col l8 m12">
            <img class="exp_image" src="{% static 'images/allele_IGHJ_distribution.png' %}" >
        </div>
      </div>
    </div>

    <!-- Heterozygous Section -->

    <div class="w3-row">
        <div class="w3-container">
            <div class="w3-col l8 m12">
                <img class="exp_image" src="{% static 'images/heterozygosity2.png' %}">
            </div>
            <div class="w3-col l4 m12" style="padding-left: 20px">
              <h1 class="xlarge-font"><b>Heterozygosity</b></h1>
              <h1 class="large-font" style="color:MediumSeaGreen;"><b>Heterozygosity abundance for each gene in the samples of interest</b></h1>
            </div>
        </div>
    </div>

    <!-- The Gene usage Section -->

    <div class="w3-row">
        <div class="w3-container">
        <div class="w3-col l3 m12">
          <h1 class="xlarge-font"><b>Gene Usage</b></h1>
          <h1 class="large-font" style="color:MediumSeaGreen;"><b>gene deletion</b></h1>
        </div>
        <div class="w3-col l9 m12">
            <img class="exp_image" src="{% static 'images/gene_usage_explore.png' %}">
        </div>
      </div>
    </div>


    <!-- ################################################################ -->
    <!-- button for search engine -->
    <!-- ################################################################ -->

     <div class="button-final">
         <a class="button secondary" href="{% url 'database:sample-data' %}" style="color: #fff;">
             <i class="fa fa-laptop" aria-hidden="true" style="margin-right:10px; color:#fff;"></i>
             Try VDJbase Search engine <span class="min-md">now</span></a>
     </div>

    {% include 'static_footer.html' %}
</div>
</body>

<!-- Script for datasets summary -->

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">

      // Load Charts and the corechart and barchart packages.
      google.charts.load('current', {'packages':['corechart']});

      // Draw the pie chart and bar chart when Charts is loaded.
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {

        var data = new google.visualization.DataTable();
        var diagnosis_contex = {{Diagnosis_list|safe}};
        data.addColumn('string', 'Topping');
        data.addColumn('number', 'Quantity of subjects');
        data.addRows(diagnosis_contex);


        var data2 = new google.visualization.DataTable();
        var sex_contex = {{Sex_list|safe}};
        data2.addColumn('string', 'Topping');
        data2.addColumn('number', 'Quantity of subjects');
        data2.addRows(sex_contex);

        var data3 = new google.visualization.DataTable();
        var cellType_contex = {{Celltype_list|safe}};
        data3.addColumn('string', 'Topping');
        data3.addColumn('number', 'Quantity of samples');
        data3.addRows(cellType_contex);

        var data4 = new google.visualization.DataTable();
        var tissue_contex = {{Tissue_list|safe}};
        data4.addColumn('string', 'Topping');
        data4.addColumn('number', 'Quantity of samples');
        data4.addRows(tissue_contex);


        var piechart_options = { title:'Diagnosis (% individuals)',
                       //width:600,
                       //height:500,
                       chartArea: {left: 0, width: '100%'},
                       width: '100%',
                       colors: ['#009999', '#00e6e6', '#80ffff', '#00cc66', '#003311','#99ffbb','#00bfff','#004d66','#66ffcc', '#004d99','#00dad8',"#88d8b0","#ffeead","#005f65","Salmon","#99ff66","#bfb2f2","#FFFFCC","#FFCC99"],
                           titleTextStyle: {
						color: 'black',    // any HTML string color ('red', '#cc00cc')
						fontName: 'Times New Roman', // i.e. 'Times New Roman'
						fontSize: 20, // 12, 18 whatever you want (don't specify px)
						bold: true,    // true or false
						italic: false   // true of false
					}};
        var piechart = new google.visualization.PieChart(document.getElementById('piechart_div'));
        piechart.draw(data, piechart_options);

        var barchart_options = {title:'Sex (no. individuals)',
                       //width:600,
                       //height:500,
                       chartArea: {left: 70, width: '100%'},
                       width: '100%',
                       legend: 'none',
                       colors: ['#99d6ff', '#0099ff', '#003d66'],
                       titleTextStyle: {
						color: 'black',    // any HTML string color ('red', '#cc00cc')
						fontName: 'Times New Roman', // i.e. 'Times New Roman'
						fontSize: 20, // 12, 18 whatever you want (don't specify px)
						bold: true,    // true or false
						italic: false   // true of false
						}};
        var barchart = new google.visualization.BarChart(document.getElementById('barchart_div'));
        barchart.draw(data2, barchart_options);

        var piechart_options3 = {title:'B Cell Type (% samples)',
                       //width:600,
                       //height:500,
                       // legend: 'none',
                       chartArea: {left: 25, width: '100%'},
                       width: '100%',
                       colors: ['#009999', '#00e6e6', '#80ffff', '#00cc66', '#003311','#99ffbb','#00bfff','#004d66','#66ffcc', '#004d99'],
                       titleTextStyle: {
						color: 'black',    // any HTML string color ('red', '#cc00cc')
						fontName: 'Times New Roman', // i.e. 'Times New Roman'
						fontSize: 20, // 12, 18 whatever you want (don't specify px)
						bold: true,    // true or false
						italic: false   // true of false
                       }};
        var piechart3 = new google.visualization.PieChart(document.getElementById('piechart_div3'));
        piechart3.draw(data3, piechart_options3);

        var piechart_options4 = { title:'Tissue (% samples)',
                       //width:200,
                       //height:200,
                       // legend: 'none',
                       chartArea: {left: 0, width: '100%'},
                       width: '100%',
                       colors: ['#009999', '#00e6e6', '#80ffff', '#00cc66', '#003311','#99ffbb','#00bfff'],
                           titleTextStyle: {
						color: 'black',    // any HTML string color ('red', '#cc00cc')
						fontName: 'Times New Roman', // i.e. 'Times New Roman'
						fontSize: 20, // 12, 18 whatever you want (don't specify px)
						bold: true,    // true or false
						italic: false   // true of false
					}};
        var piechart4 = new google.visualization.PieChart(document.getElementById('piechart_div4'));
        piechart4.draw(data4, piechart_options4);
      }

$(window).resize(function(){
  drawChart();
});

</script>

</html>

database/templates/licensing.html
{% load static %}


<!doctype html>
<html lang=”en”>


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Explore Data</title>

    {% include 'links.html' %}

    <link rel="stylesheet" href="{% static 'css/vdjbase.css' %}">
    <link rel="stylesheet" href="{% static 'css/user_guide.css' %}">
</head>

<!-- ################################# body ######################## -->

<body>
{% include 'navbar.html' %}

<div class="w3-content" style="max-width:1100px">
    <div class="w3-container"  style="text-align:center; padding-top: 60px">

        <h1 style="color:#009999;font-size:300%; padding-bottom: 60px"><b>Licensing</b></h1>

        <h1 style="color: black;font-size:200%"><b>Content</b></h1>
        <p style="font-size:150%; padding-bottom: 60px">
            Information provided on this site is published under a <a href="https://creativecommons.org/publicdomain/zero/1.0/legalcode" target="_blank">CC0 (Creative Commons 0) license</a>.
        </p>
        <h1 style="color: black;font-size:200%"><b>Source Code</b></h1>
        <p style="font-size:150%">
            The website source code is published under a <a href="https://perma.cc/DK5U-NDVE" target="_blank">European Union Public License v. 1.2</a> and is available from <a href="https://bitbucket.org" target="_blank">Bitbucket</a>.
        </p>
    </div>
</div>
</body>
</html>

database/templates/links.html
{% load static %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="shortcut icon" href={% static 'images/favicon.ico' %} type="image/x-icon">
<link rel="icon" href={% static 'images/favicon.ico' %} type="image/x-icon">

database/templates/navbar.html
<!-- Navbar -->

{% load static %}

<div class="w3-top" id="pinned_nav">
    <div class="w3-bar w3-black">
        <a href="{% url 'database:home' %}"><img class="w3-bar-item w3-left w3-hide-small" src="{% static 'images/logo_black2.png' %}" alt="VDJlogo" style="width:9%" /></a>
        <a href="{% url 'database:home' %}#" class="w3-bar-item w3-button w3-padding-large ">Home</a>

        <div class="w3-dropdown-hover w3-hide-small sample-down">
            <button class="w3-padding-large w3-button" title="Tables">Database Search <i class="fa fa-caret-down"></i></button>
            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                <a href="{% url 'database:sample-data' %}" class="w3-bar-item w3-hide-small w3-button" target="">Samples</a>
                <a href="{% url 'database:allele-data' %}" class="w3-bar-item w3-hide-small w3-button" target="">Alleles</a>
            </div>
        </div>

        <a href="{% url 'database:explore-data' %}" class="w3-bar-item w3-hide-small w3-button w3-padding-large">Explore Data </a>
        <a href="{% url 'database:user-guide' %}" class="w3-bar-item w3-hide-small w3-button w3-padding-large">User Guide </a>

        <div class="w3-dropdown-hover w3-hide-small sample-down">
            <button class="w3-padding-large w3-button" title="Tables">About <i class="fa fa-caret-down"></i></button>
            <div class="w3-dropdown-content w3-bar-block w3-card-4">
                <a href="{% url 'database:home' %}#contact" class="w3-bar-item w3-hide-small w3-button w3-padding-large">Contact us</a>
                <a href="{% url 'database:home' %}#add" class="w3-bar-item w3-hide-small w3-button w3-padding-large">Contribute dataset</a>
                <a href="{% url 'database:home' %}#versions" class="w3-bar-item w3-hide-small w3-button w3-padding-large">Versions</a>
                <a href="{% url 'database:licensing' %}" class="w3-bar-item w3-hide-small w3-button w3-padding-large">Licensing</a>
            </div>
        </div>
        <a href="javascript:void(0)" class="w3-bar-item w3-button w3-right w3-hide-large w3-hide-medium" onclick="mobileNav()">&#9776;</a>
    </div>

    <div id="mobile_nav" class="w3-hide w3-hide-large w3-hide-medium">
        <div class="w3-bar w3-black">
            <a href="{% url 'database:home' %}#" class="w3-bar-item w3-mobile w3-button w3-padding-large ">Home</a>
            <a href="{% url 'database:sample-data' %}" class="w3-bar-item w3-mobile w3-button" target="">Samples</a>
            <a href="{% url 'database:allele-data' %}" class="w3-bar-item w3-mobile w3-button" target="">Alleles</a>
            <a href="{% url 'database:explore-data' %}" class="w3-bar-item w3-mobile w3-button w3-padding-large">Explore Data </a>
            <a href="{% url 'database:user-guide' %}" class="w3-bar-item w3-mobile w3-button w3-padding-large">User Guide </a>
            <a href="{% url 'database:home' %}#contact" class="w3-bar-item w3-mobile w3-button w3-padding-large">Contact us</a>
            <a href="{% url 'database:home' %}#add" class="w3-bar-item w3-mobile w3-button w3-padding-large">Contribute dataset</a>
            <a href="{% url 'database:home' %}#versions" class="w3-bar-item w3-mobile w3-button w3-padding-large">Versions</a>
            <a href="{% url 'database:licensing' %}" class="w3-bar-item w3-mobile w3-button w3-padding-large">Licensing</a>
        </div>
    </div>
</div>


<div id="pinned_height" style="padding-top:0px;"></div>

<script>
    function getHeight() {
      var nav = document.getElementById("pinned_nav");
      var nav_height = nav.offsetHeight; //append this var where you need to.
      $("#pinned_height").css('padding-top', nav_height+'px')
    };

    $(document).ready(function(){
      getHeight();
    });

    $(window).resize(function(){
      getHeight();
    });

    function mobileNav() {
      $("#mobile_nav").toggleClass('w3-show')
    }
</script>

database/templates/static_footer.html
{% load static %}

<div class="w3-panel w3-border-top w3-border-black">
<div class="w3-cell-row" style="height:10px">
    <div class="w3-light-grey w3-container w3-padding-16 w3-cell w3-mobile" style="width:33%">
        <img src="{% static 'images/homepage_logo_3.png' %}"  style="max-height: 70px">
    </div>
    <div class="w3-light-grey w3-container w3-cell w3-mobile" style="width:33%;vertical-align: middle">
        <a href="{% url 'database:licensing' %}"><h3>Licensing</h3></a>
    </div>
    <div class="w3-light-grey w3-container w3-cell w3-mobile" style="width:33%;vertical-align: middle;">
        <a href="#" class="w3-button w3-black w3-margin"><i class="fa fa-arrow-up w3-margin-right"></i>Back to top</a>
    </div>
</div>
</div>