database/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from website import settings
from . import views
app_name = 'database'

urlpatterns = [
    url(r'^$', views.index, name='home'),

    # tables
    url(r'^data/Samples$', views.sample_table.as_view(), name='sample-data'),
    url(r'^data/Alleles$', views.alleles_table.as_view(), name='allele-data'),

    url(r'^Graph/', views.presenting_graph.as_view(), name='graph-present'),

    # genotype urls handler
    url(r'^genotype/(?P<sample_name>[\w\-]+)$', views.down_geno, name='down-geno'),
    url(r'^genotype_graph/(?P<sample_name>[\w\-]+)/(?P<html>[0-1])$', views.genotype_graph, name='geno-graph'),
    url(r'^genotype_stats/(?P<sample_name>[\w\-]+)$', views.down_geno_stats, name='down-stats'),

    # hapotype urls handler
    url(r'^haplotype/(?P<id>[\w\-]+)$', views.down_haplotype, name='down-haplotype'),
    url(r'^haplotype_graph/(?P<id>[\w\-]+)/(?P<html>[0-1])$', views.haplotype_graph, name='haplotype-graph'),
    url(r'^User_Guide/', views.guide.as_view(), name='user-guide'),

    url(r'^Explore_Data$', views.explore.as_view(), name='explore-data'),

    url(r'^Licensing$', views.licensing.as_view(), name='licensing'),
]


#user handler add to url patterns in case of adding users
"""
    url(r'^register$', views.UserFormView.as_view(), name='register'),
    url(r'^login$', views.login.as_view(), name='login'),
    url(r'^logout$', views.logout, name='logout'),"""

website/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('database.urls')),

]

database/views.py
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import View
from django.contrib import messages
from django.db.models import Q, Count
from urllib import parse

from .forms import *
from scripts import graphs, export_data, exportR_data, export_genotypes
from website.settings import SCRATCH_ROOT, BASE_DIR, APACHE_SEND
from .hold_global_vars import *

from itertools import chain
from wsgiref.util import FileWrapper
from collections import defaultdict

from datetime import datetime
import zipfile, os, math, datetime
import json

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import generic_dna

from io import StringIO

from .apps import commit_id
from .novel_checks import check_novel_confidence

##########################################################################################################
#
#     ********************* SEND FILE ********************************
#
#     Send file via apache mod_xsendfile, or stream if we don't have it
#
##########################################################################################################

def send_file(filename, content_type, disposition):
    if APACHE_SEND:
        resp = HttpResponse()
        resp['X-Sendfile'] = filename
    else:
        # check that the file is in a configured location
        if os.path.join(BASE_DIR, 'uploads') not in filename and SCRATCH_ROOT not in filename:
            print('Only files in BASE_DIR/uploads and SCRATCH_ROOT can be sent to the user.')
            return ''
        resp = HttpResponse(open(filename, 'rb').read())

    resp['Content-Type'] = content_type
    resp['Content-Disposition'] = disposition
    return resp


##########################################################################################################
#
#     ********************* HOMEPAGE ********************************
#
##########################################################################################################

def index(request):
    template = 'homepage.html'
    all_gene = Gene.objects.all()
    context = {'all_gene': all_gene, 'commit_id': commit_id}
    return render(request, template,  context)


##########################################################################################################
#
#     ********************* SAMPLES PAGE ********************************
#
##########################################################################################################

class sample_table(View):
    template_name = 'tables/samples.html'
    form_class = SamplesSearchForm
    advance = SamplesAdvanceSearchForm
    filter_by_gene = SampleFilterByGene
    filter_samples_by_gene = SampleFilterByAlleles
    haplotype_graph_form = HaplotypeGraphForm

    ##########################################################################################################
    #
    #     ****************** EXPORT THE DATA THROUGH ZIP FILE *****************************
    #
    ##########################################################################################################

    def export_sample_table(self, name, all_samples):
        genotypes_folder = "Genotypes"
        genotypes_stats_folder = "Genotypes_stats"
        haplotypes_folder = "Haplotypes"

        titles = ["SAMPLE", "SUBJECT", "NAME_IN_PAPER", "SEX", "AGE", "ETHNICITY", "STUDY_GROUP", "DIAGNOSIS", "ORGANISM",
                  "TISSUE", "CELL_TYPE", "CELL_SUBSET_TYPE", "ISOTYPE", "TARGET_LOCUS(IG)", "TARGET_SUBSTRATE", "UMI", "SEQUENCING_PLATFORM",
                  "SEQUENCING_LENGTH", "REVERSE_PCR_PRIMER_LOCATION", "FORWARD_PCR_PRIMERS_LOCATION", "TOTAL_READS", "PROJECT",
                  "LAB_ADDRESS", "RESEARCHER", "NUMBER_OF_SUBJECTS", "NUMBER_OF_SAMPLES", "PAPER", "CONTACT",
                  "STUDY_ID", "PUBLICATION_URL", "Preprocessing", "ALIGNER_TOOL", "ALIGNER_VERSION",
                  "GERMLINE_GENE_SET", "GENOTYPING_TOOL", "GENOTYPING_VERSION", "HAPLOTYPING_TOOL", "HAPLOTYPING_VERSION",
                  "GENOTYPE_FILE", "GENOTYPE_STATISTICS", "HAPLOTYPE_BY", "HAPLOTYPE_FILES"]

        samples = []
        genotypes = []
        genotypes_stats = []
        haplotypes = []

        for s in all_samples:
            sample = []
            sample.append(s.name)

            patient = s.patient
            sample += [patient.name, patient.name_in_paper, patient.sex, patient.age, patient.ethnic, patient.cohort, patient.status]

            tissue = s.tissue_pro
            sample += [tissue.species, tissue.tissue, tissue.cell_type, tissue.sub_cell_type, tissue.isotype]
            sample.append(s.chain)

            protocol = s.seq_protocol
            sample += [protocol.helix, protocol.umi, protocol.sequencing_platform, protocol.sequencing_length,
                       protocol.primers_3_location, protocol.primers_5_location]
            sample.append(s.row_reads)

            study = s.study
            sample += [study.name, study.institute, study.researcher, study.num_subjects, study.num_samples,
                        study.reference, study.contact, study.accession_id, study.accession_reference]

            geno = s.geno_detection
            sample += [geno.prepro_tool, geno.aligner_tool, geno.aligner_ver, geno.aligner_reference, geno.geno_tool,
                       geno.geno_ver, geno.haplotype_tool, geno.haplotype_ver]

            sample.append(os.path.join(genotypes_folder, os.path.basename(s.genotype.name)))
            genotypes.append(s.genotype.name)
            if s.genotype_stats:
                sample.append(os.path.join(genotypes_stats_folder, os.path.basename(s.genotype_stats.name)))
                genotypes_stats.append(s.genotype_stats.name)
            else:
                sample.append("")

            haplotypes_by = []
            haplotypes_files = []

            if s.haplotype:
                for hap_file in s.haplotype.all():
                    haplotypes.append(hap_file.file.name)
                    haplotypes_files.append(os.path.join(haplotypes_folder, os.path.basename(hap_file.file.name)))
                    haplotypes_by.append(hap_file.by_gene)


            haplotypes_by = ", ".join(haplotypes_by)
            haplotypes_files = ", ".join(haplotypes_files)

            sample.append(haplotypes_by)
            sample.append(haplotypes_files)

            # append the list of fileds of one sample into the table f samples
            samples.append(sample)

        metafile = export_data.output("metadata.tab", titles, samples)
        name = os.path.join(SCRATCH_ROOT, name) + '.zip'

        with zipfile.ZipFile(name, 'w') as myzip:
            myzip.write(metafile, os.path.basename(metafile))
            for f in genotypes:
                path = os.path.join(BASE_DIR, 'uploads/', f)
                myzip.write(path, os.path.join(genotypes_folder, os.path.basename(path)))
            for hap in haplotypes:
                path = os.path.join(BASE_DIR, 'uploads/', hap)
                myzip.write(path, os.path.join(haplotypes_folder, os.path.basename(path)))
            for geno_stats in genotypes_stats:
                path = os.path.join(BASE_DIR, 'uploads/', geno_stats)
                myzip.write(path, os.path.join(genotypes_stats_folder, os.path.basename(path)))

            myzip.close()

        return send_file(name, 'application/zip', 'Content-Disposition')

    ##########################################################################################################
    #
    #     genotypes_graph - CREATE MULTIPLE GENOTYPES AND EXPORT
    #
    ##########################################################################################################

    def genotypes_graph(self, request, name, samples, genes, file_type, with_pseudo_genes):
        samples = samples.values_list('name', 'genotype')
        genes = genes.values_list('name')
        genes = list(chain.from_iterable(genes))
        with_pseudo_genes = bool(with_pseudo_genes)

        genotypes_graph = export_genotypes.merge_genotypes(samples, name, genes, type_html=file_type, pseudo_genes=with_pseudo_genes)

        if not genotypes_graph:
            return False

        if not file_type:
            return send_file(genotypes_graph, 'application/pdf', 'attachment; filename=genotypes_graph.pdf')
        else:
            genotypes_graph = genotypes_graph.split("graphs/")[1]
            template = "temp/display_genotype.html"
            context = {'html_file': genotypes_graph, }
            return render(request, template, context)


    ##########################################################################################################
    #
    #     genotypes_heatmap - CREATE HEATMAP GENOTYPES AND EXPORT
    #
    ##########################################################################################################

    def genotypes_heatmap(self, request, name, samples, genes, kdiff, file_type):
        samples = samples.values_list('name', 'genotype')
        genes = genes.values_list('name')
        genes = list(chain.from_iterable(genes))
        genotypes_graph = export_genotypes.genotypes_heatmap(samples, name, genes, kdiff, type_html=file_type)

        if not genotypes_graph:
            return False

        if not file_type:
            return send_file(genotypes_graph, 'application/pdf', 'attachment; filename=genotypes_heatmap.pdf')
        else:
            genotypes_graph = genotypes_graph.split("graphs/")[1]
            template = "temp/display_genotype.html"
            context = {'html_file': genotypes_graph, }
            return render(request, template, context)


    ##########################################################################################################
    #
    #     haplotypes_heatmap - CREATE MULTIPLE HAPLOTYPES HEATMAP AND EXPORT
    #

database/templates/temp/Error_message.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'links.html' %}
    <link rel="stylesheet" href="{% static 'css/vdjbase.css' %}">

    <style>
    iframe{
        width: 100%;
        height: 900px;
    }
    </style>
</head>

<body>
{% load static %}
{% include 'navbar.html' %}

<h1>Error:</h1>
<div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

</body>
</html>

database/templates/temp/display_genotype.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include 'links.html' %}
    <link rel="stylesheet" href="{% static 'css/vdjbase.css' %}">

    <style>
    iframe{
        width: 100%;
        height: 900px;
    }
    </style>
</head>

<body>
{% load static %}
{% include 'navbar.html' %}

    <iframe src="{% url 'database:graph-present' %}{{ html_file }}" frameBorder="0"></iframe>
</body>
</html>

database/templates/temp/graphs_present.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VDJbase</title>
    {%  include 'links.html' %}
    <link rel="stylesheet" href="{% static 'css/vdjbase.css' %}">
    <style>
        iframe{
        width: 33%;
        height: 900px;
        }
    </style>
</head>
<body>
{% include 'navbar.html' %}

{% for col in srcs %}
    <div>
    {% for s in col %}
      <iframe src="{% url 'database:graph-present' %}{{ s }}" frameBorder="0"></iframe>
    {% endfor %}
    </div>
{% endfor %}
</body>
</html>

database/templates/temp/modals.html
    <!-- The Modal of messages -->
<div class="modal" id="message_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
          <h4 class="modal-title">Warning</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
              {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
            <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
    </div>
  </div>
</div>


    <!-- The Modal of Genotype -->
<div class="modal" id="genotype_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Genotype graph</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div class="form-group" style="margin-right: 10px;">
              <label class="control-label" id="control-graph-type">Type of graph:</label>
              <div class="modal-section">
                   <input type="radio" name="geno-type" value="heat" checked="checked">&nbsp;Heat map (all selected samples)<br>
                   <input type="radio" name="geno-type" value="list">&nbsp;List of genotypes (up to 20 selected samples)<br>
               </div>
              <label class="control-label">Showing graphs for:</label>
              <div class="modal-section">
                   <input type="radio" name="geno-select" value="sample" checked="checked">&nbsp;Each sample<br>
                   <input type="radio" name="geno-select" value="individual">&nbsp;Individual (takes representative sample for each subject)<br>
              </div>
              <label class="control-label" id="control-file-type">File type:</label>
              <div class="modal-section">
                  <input type="radio" name="genofile-type" value="pdf" checked="checked">&nbsp;PDF<br>
                  <input type="radio" name="genofile-type" value="html">&nbsp;HTML<br>
               </div>
              <label class="control-label">Kdiff threshold:</label> <input type="number" min=0 step=0.1 value=0 name="geno-k">
              <p  style="margin-top: 30px">Note: HTML output is interactive, but can take time to generate for large sample selections.</p>

          </div>
      </div>
      <!-- Modal footer -->
      <div class="modal-footer">
           <button class="action_btn w3-container w3-center w3-round-xlarge w3-teal" style="width:90%" type="submit" name="action" value="Geno">Generate graph</button>
      </div>

    </div>
  </div>
</div>


    <!-- The Modal of Haplotypes -->
<div class="modal" id="haplotype_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Haplotypes graphs</h4>
        <div>*Note: The graph will only be done just for the samples whose haplotype is done by the selected anchor.<br>
            &nbsp;It's recommended to filter the samples by the filed "Haplotype by" first.</div>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div id="filter_haplotypes" style="">
              <label class="control-label">Showing graphs for:</label>
              <div class="modal-section">
                   <input type="radio" name="haplo_select" value="sample" checked="checked">&nbsp;Each sample<br>
                   <input type="radio" name="haplo_select" value="individual">&nbsp;Individual (takes representative sample for each subject)<br>
              </div>
               {% for field in haplotype_graph_form %}
               <div class="form-haplo" style="margin-right: 10px;">
                   <label class="control-label" id="{{field.name}}">{{field.label_tag}}  <p class="fa fa-caret-down"></p></label>
                   <div id="search-{{field.name}}">{{field}}</div>
               </div>
               {% endfor %}
           </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
           <button class="action_btn w3-container w3-center w3-round-xlarge w3-teal" style="width:90%" type="submit" name="action" value="haplo">Generate graph</button>
      </div>

    </div>
  </div>
</div>


    <!-- The Modal of Allele distribution -->
<div class="modal" id="Allele_dis_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Allele distribution graph</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div class="form-group" style="margin-right: 10px;">
              <label class="control-label" id="allele-dis-graph-amb">Ambiguous alleles:</label>
              <div class="modal-section">
                   <input type="radio" name="allele-dis-amb" value=0 checked="checked">&nbsp;Exclude<br>
                   <input type="radio" name="allele-dis-amb" value=1>&nbsp;Include <br>
              </div>
              <label class="control-label" id="allele-dis-graph-novel">Novel alleles:</label>
              <div class="modal-section">
                   <input type="radio" name="allele-dis-novel" value=0>&nbsp;Exclude<br>
                   <input type="radio" name="allele-dis-novel" value=1 checked="checked">&nbsp;Include <br>
              </div>
          </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
           <button class="action_btn w3-container w3-center w3-round-xlarge w3-teal" style="width:90%" type="submit" name="action" value="alleles">Generate graph</button>
      </div>

    </div>
  </div>
</div>


    <!-- The Modal of Heterozygous -->
<div class="modal" id="Hetero_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Heterozygous graph</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div class="form-group" style="margin-right: 10px;">
              <label class="control-label" id="hetero-graph-alleles">Ambiguous alleles:</label>
              <div class="modal-section">
                   <input type="radio" name="hetero-amb" value=0 checked="checked">&nbsp;Exclude<br>
                   <input type="radio" name="hetero-amb" value=1>&nbsp;Include <br>
              </div>
          </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
           <button class="action_btn w3-container w3-center w3-round-xlarge w3-teal" style="width:90%" formtarget="_blank" type="submit" name="action" value="hetero">Generate graph</button>
      </div>

    </div>
  </div>
</div>


    <!-- The Modal of Alleles usage -->
<div class="modal" id="allele_usage_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Alleles Usage graph</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div class="form-group" style="margin-right: 10px;">
              <label class="control-label" id="usage-graph-alleles">Ambiguous alleles:</label>
              <div class="modal-section">
                   <input type="radio" name="usage-amb" value=0 checked="checked">&nbsp;Exclude<br>
                   <input type="radio" name="usage-amb" value=1>&nbsp;Include <br>
              </div>
          </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
           <button class="action_btn w3-container w3-center w3-round-xlarge w3-teal" style="width:90%" formtarget="_blank" type="submit" name="action" value="gene_alleles">Generate graph</button>
      </div>

    </div>
  </div>
</div>


<!-- The Modal of frequencies -->
<div class="modal" id="freqs_modal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Gene usage graph</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
          <div class="form-group" style="margin-right: 10px;">
              <label class="filter_label" id="control-label-dots">Display frequencies using:</label>
              <div class="modal-section">
                   <input type="radio" name="freq-dot" value=0 checked="checked">&nbsp;One sample from each selected subject<br>
                   <input type="radio" name="freq-dot" value=1>&nbsp;All selected samples<br>
               </div>
              <label class="filter_label" id="control-label-calc">Calculate frequencies by:</label>
              <div class="modal-section">
                   <input type="radio" name="calc-freq" value=0 checked="checked">&nbsp;Number of clones<br>
                   <input type="radio" name="calc-freq" value=1>&nbsp;Number of sequences<br>
               </div>
               <p>Note: Advanced Filters are not applied to this graph.</p>
          </div>
      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
           <button class="action_btn w3-container w3-center w3-round-xlarge w3-teal" class="close" style="width:90%" type="submit" name="action" value="freqs">Generate graph</button>
      </div>

    </div>
  </div>
</div>

database/templates/temp/search_form_advance.html
<style>
    button {
        margin-top: 22px;
        margin-left: 10px;
    }
    span.fields{
        margin-right: 28px;
    }
</style>

{% block search %}
    {% csrf_token %}
    <div class="fields">
        {% for field in advance %}
         <div class="form-group" style="margin-right: 10px">
            <label class="control-label">{{field.label_tag}}</label>
            <div class="search-field" id="1search_box">{{field}}</div>
            <span class="text-danger small">{{field.errors}}</span>
         </div>
        {% endfor %}
        <input type="submit" name="action" value="submit" hidden>
    </div>
{% endblock %}

database/templates/temp/search_form_bottom.html
<style>
    button{
        cursor: pointer;
        margin-left: 1px;
    }
    .button{{ page }} {
        opacity: 0.6;
        cursor: not-allowed;
    }
</style>
{% block chooce-pages %}
    {% if pages %}
        <div class="w3-row" style="padding-bottom: 24px;">
            <div class="col-md-offset-0">
                <button type="submit" class="button{{ prev }}" name="page" value="{{ prev }}" style="margin-left: 15px"><div class="glyphicon glyphicon-triangle-left"></div></button>
                {% for p in pages %}
                        <button type="submit" class="button{{ p }}" name="page" value="{{ p }}" >{{ p }}</button>
                {% endfor %}
                <button type="submit" class="button{{ next }}" name="page" value="{{ next }}"><div class="glyphicon glyphicon-triangle-right"></div></button>
            </div>
        </div>
    {% endif %}
{% endblock %}

database/templates/temp/search_form_up.html
<style>
    button {
        margin-top: 22px;
        margin-left: 10px;
    }
    span.fields{
        margin-right: 28px;
    }
</style>

{% block search %}
    <span class="fields">
        {% for field in form %}
        <div class="form-group" style="margin-right: 10px">
            <label class="control-label">{{field.label_tag}}</label>
            <div class="search-field" id="search_box">{{field}}</div>
            <span class="text-danger small">{{field.errors}}</span>
        </div>
        {% endfor %}
        <input type="submit" name="action" value="submit" hidden>
    </span>
{% endblock %}

database/templates/temp/table_fields.html
<tr>
    {% for field in form %}
    <th>{{field.label}}</th>
    {% endfor %}
</tr>

database/templates/temp/updateTemp.html
{% for field in form %}
    <div class="form-group" style="margin: 15px">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{field.errors}}</span>
        </div>
      <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
{% endfor %}